# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import zkp_auth_pb2 as zkp__auth__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in zkp_auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/zkp_auth.Auth/Register',
                request_serializer=zkp__auth__pb2.RegisterRequest.SerializeToString,
                response_deserializer=zkp__auth__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.CreateAuthenticationChallenge = channel.unary_unary(
                '/zkp_auth.Auth/CreateAuthenticationChallenge',
                request_serializer=zkp__auth__pb2.AuthenticationChallengeRequest.SerializeToString,
                response_deserializer=zkp__auth__pb2.AuthenticationChallengeResponse.FromString,
                _registered_method=True)
        self.VerifyAuthentication = channel.unary_unary(
                '/zkp_auth.Auth/VerifyAuthentication',
                request_serializer=zkp__auth__pb2.AuthenticationAnswerRequest.SerializeToString,
                response_deserializer=zkp__auth__pb2.AuthenticationAnswerResponse.FromString,
                _registered_method=True)


class AuthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAuthenticationChallenge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyAuthentication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=zkp__auth__pb2.RegisterRequest.FromString,
                    response_serializer=zkp__auth__pb2.RegisterResponse.SerializeToString,
            ),
            'CreateAuthenticationChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAuthenticationChallenge,
                    request_deserializer=zkp__auth__pb2.AuthenticationChallengeRequest.FromString,
                    response_serializer=zkp__auth__pb2.AuthenticationChallengeResponse.SerializeToString,
            ),
            'VerifyAuthentication': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyAuthentication,
                    request_deserializer=zkp__auth__pb2.AuthenticationAnswerRequest.FromString,
                    response_serializer=zkp__auth__pb2.AuthenticationAnswerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zkp_auth.Auth', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zkp_auth.Auth', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Auth(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkp_auth.Auth/Register',
            zkp__auth__pb2.RegisterRequest.SerializeToString,
            zkp__auth__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAuthenticationChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkp_auth.Auth/CreateAuthenticationChallenge',
            zkp__auth__pb2.AuthenticationChallengeRequest.SerializeToString,
            zkp__auth__pb2.AuthenticationChallengeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyAuthentication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkp_auth.Auth/VerifyAuthentication',
            zkp__auth__pb2.AuthenticationAnswerRequest.SerializeToString,
            zkp__auth__pb2.AuthenticationAnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
